### PR TITLE
Precompiled lib, use webpack and update dependency versions

### PR DESCRIPTION
**Pull request by scags9876**
Some useful stuff in here, thought others might benefit from these changes.

 - using webpack instead of grunt and browserify
 - including babelfied lib
 - upgrading dependencies to work with react 15
 - upgrade to lodash 4.x

### CODE REVIEW

**Comment by scags9876** [comment]
Addresses:
 - #23 
 - #19 
 - #21

**Comment by MandarinConLaBarba** [comment]
Thanks very much for this! I am out of town for a week but will review this when I get back..

**Comment by MandarinConLaBarba** [comment]
@scags9876 running `webpack` doesn't appear to create transpiled `.js` for distribution, which seems to be what #23 and #19 call for. Running `webpack` creates a bundle that includes the example application, but that isn't what we'd want to ship with `npm publish`.

**Comment by scags9876** [comment]
@MandarinConLaBarba sorry for the late response, been a busy week.  I believe the command to use is `npm run prepublish`  I add a small section to the readme to explain the various npm commands.  😸

**Comment by MandarinConLaBarba** [comment]
Great, thanks. I would think that the transpiled code would be included in the npm package, but not in source. Meaning, lib/*.js would be in `.gitignore` so that it would be kept out of the repository. Thoughts?

**Comment by scags9876** [comment]
Ah yes, you are correct @MandarinConLaBarba .   I'm using it checked in so that I can import directly from github:

```
"react-tree-menu": "git://github.com/scags9876/react-tree-menu.git",
```

I can make this change... I might need to submit a new PR for it though since I'd like to do it in a branch of my fork so that I can continue to import my master until you merge this.

**Comment by scags9876** [comment]
Ok, https://github.com/MandarinConLaBarba/react-tree-menu/pull/32 has been opened and replaces this PR

**Pull request closed without merging**
